### ISSUE TITLE
Installing pre-compiled releases using Github Actions

### ISSUE THREAD

**Issue by jtgrasb** [FloatingArrayDesign/MoorDyn#285]
Hi all, I am trying to install the pre-compiled releases in GitHub Actions in order to keep the [WEC-Sim/MoorDyn](https://github.com/WEC-Sim/MoorDyn) repository updated with this one. I am still getting familiar with Github Actions, but I am testing the options on some private repositories. Here is my example code so far:

```

name: Compile MoorDyn Libraries
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - run_compile
jobs:
  pull-file:
    runs-on: ubuntu-latest
    steps:
      - name: Download release asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'jtgrasb/test'
          version: 'tags/1'
          file: 'Moordyn-2.3.7-win64.exe'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Upload file for next job
        uses: actions/upload-artifact@v4
        with:
          name: asset_exe
          path: Moordyn-2.3.7-win64.exe
  run-exe:
    needs: pull-file
    runs-on: windows-latest
    steps:
      - name: Download file from previous job
        uses: actions/download-artifact@v4
        with:
          name: asset_exe
      - name: List workspace
        run: |
          dir 
      - name: Create output directory
        run: |
          mkdir output
      - name: Run exe
        run: |
          .\Moordyn-2.3.7-win64.exe --output-dir=.\output
          echo "Exit code: $?"
      - name: List workspace
        run: |
          dir .\output
```

The exe seems to be running, but the output directory is not being populated. Is there another command I need to include to access the outputs of the exe? @RyanDavies19 Let me know if you have any suggestions.
